language: c

env:
  - CXX=g++-6
  - C

compiler:  
    - gcc
    - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - uuid-dev

install: 
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq lcov curl
script:
  - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Debug ../cmake_all && cmake --build .


notifications:
  webhooks:
    urls:
      - # https://webhooks.gitter.im/e/8784d70ae92882b8923a
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always